services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
